export default {
	UNAUTHENTICATED: "YOU ARE NOT SIGNED IN",
    AUTHENTICATED: "YOU ARE ALREADY SIGNED IN",
	INCOMPLETE_ROUND: "ROUND INCOMPLETE",

	ADMIN_UNAUTHENTICATED: "WRONG ADMIN SECRET",
	INVALID_SECRET:
		"NO SECRET HAS BEEN PROVIDED, OR PROVIDED SECRET IS OF WRONG FORMAT",
};
