version: "3.8"
services:
    postgres:
        image: postgres
        ports:
            - 5431:5432
        environment:
            - POSTGRES_PASSWORD=password
    pgadmin:
        image: dpage/pgadmin4
        ports: 
            - 5050:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=email@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=password
