version: "3.8"
services:
    postgres:
        image: postgres
        ports:
            - 5431:5432
        environment:
            - POSTGRES_PASSWORD=password
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 5050:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=email@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=password
    localstack:
        image: localstack/localstack:latest
        ports:
            - "4563-4599:4563-4599"
            - "8055:8080"
        environment:
            - SERVICES=s3
            - DEFAULT_REGION=us-east-1
        volumes:
            - "./scripts/localstackSetup.sh:/docker-entrypoint-initaws.d/make-s3.sh"
