# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    environment: development

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: DEBUG=testcontainers npm test
      env: 
        TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
        TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
        ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}

        
